# Generated by Django 5.2 on 2025-05-02 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZeroHate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('toxic', models.FloatField(default=0.0)),
                ('severe_toxic', models.FloatField(default=0.0)),
                ('obscene', models.FloatField(default=0.0)),
                ('threat', models.FloatField(default=0.0)),
                ('insult', models.FloatField(default=0.0)),
                ('identity_hate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
