# Generated by Django 5.2 on 2025-05-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZeroHate', '0004_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginotp',
            name='login_counts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
